### ISSUE TITLE
`registerDerivativeIp` fails when minting commercial

### ISSUE THREAD

**Issue by jacob-tucker** [storyprotocol/sdk#291]
If I register an IP Asset with commercial terms that have a minting fee, and then use `registerDerivativeIp`, the function does not work.

Code:
```
const derivativeTokenId = await mintNFT(account.address, 'test-uri')
    const registerIpDerivativeResponse = await client.ipAsset.registerDerivativeIp({
        nftContract: NFTContractAddress, // an nft contract in my code
        tokenId: derivativeTokenId!,
        derivData: {
            parentIpIds: [registerIpResponse.ipId as Address],
            licenseTermsIds: [registerIpResponse.licenseTermsId as bigint],
        },
        ipMetadata: {
            ipMetadataURI: 'test-uri',
            ipMetadataHash: toHex('test-metadata-hash', { size: 32 }),
            nftMetadataHash: toHex('test-nft-metadata-hash', { size: 32 }),
            nftMetadataURI: 'test-nft-uri',
        },
        txOptions: { waitForTransaction: true },
    })
    console.log(
        `Derivative IPA created at transaction hash ${registerIpDerivativeResponse.txHash}, IPA ID: ${registerIpDerivativeResponse.ipId}`
    )
```

I get the following error:

<img width="853" alt="Screenshot 2024-10-15 at 7 35 20 PM" src="https://github.com/user-attachments/assets/90f96c8c-7b67-4589-b116-ea4f858de8bf">

I then tried to instead register the child first with `register`, and then use `registerDerivative`, and that worked perfectly. So I believe it is issue with `registerDerivativeIp`

**Comment by bonnie57** [comment]
Hello @jacob-tucker,

I noticed you encountered an error message: `ERC20InsufficientAllowance(address,uint256,uint256)`. You can view the details in this [link](https://github.com/user-attachments/assets/86ba1f02-8b5d-4700-91f3-d52cc527a4ce).

To resolve this issue, you need to use the approve method in the ERC20 contract with the parameter derivativeWorkflows  address. You can [click here](https://github.com/storyprotocol/sdk/blob/dev/packages/core-sdk/test/integration/utils/mockERC20.ts#L32) to learn how to call the approve method.
